begin;
do $$ begin
  if exists(select 1 from public.matches where status in ('PRIMER_TIEMPO','DESCANSO','SEGUNDO_TIEMPO','PAUSADO')) then
    raise exception 'Prueba cancelada: hay un partido activo real.';
  end if;
end $$;
create function pg_temp.act(mid uuid,action text) returns jsonb language plpgsql as $$
declare v timestamptz; result jsonb;
begin
  select updated_at into v from public.matches where id=mid;
  execute 'set local role anon';
  result:=public.control_match(mid,action,v);
  execute 'reset role'; return result;
end $$;
create function pg_temp.second_half(mid uuid) returns void language plpgsql as $$
begin
  update public.matches set phase_started_at=clock_timestamp()-interval '20 minutes' where id=mid;
  perform pg_temp.act(mid,'BREAK');
  update public.matches set phase_started_at=clock_timestamp()-interval '6 minutes' where id=mid;
  perform pg_temp.act(mid,'SECOND_HALF');
  update public.matches set phase_started_at=clock_timestamp()-interval '20 minutes' where id=mid;
end $$;
create function pg_temp.goal(mid uuid,tid uuid) returns jsonb language plpgsql as $$
declare result jsonb;
begin
  execute 'set local role anon'; result:=public.record_goal(mid,tid,gen_random_uuid()); execute 'reset role'; return result;
end $$;
do $$
declare c uuid; d uuid; a uuid; b uuid; x uuid; y uuid; outsider uuid; regular1 uuid; regular2 uuid; regular3 uuid;
 sf1 uuid; sf2 uuid; final_id uuid; third_id uuid; result jsonb; event_id uuid; rejected boolean; qualified uuid[];
 prefix text := '__final_test_'||gen_random_uuid()::text;
begin
 select id into strict c from public.categories where name='Varones';
 if (select regular_closed_at is not null from public.categories where id=c) then raise exception 'Prueba cancelada: categoría real cerrada.'; end if;
 select id into strict d from public.matchdays where number=4;
 execute 'set local role anon';
 insert into public.teams(category_id,name) values(c,prefix||'_A') returning id into a;
 insert into public.teams(category_id,name) values(c,prefix||'_B') returning id into b;
 insert into public.teams(category_id,name) values(c,prefix||'_C') returning id into x;
 insert into public.teams(category_id,name) values(c,prefix||'_D') returning id into y;
 insert into public.teams(category_id,name) values(c,prefix||'_Z') returning id into outsider;
 insert into public.matches(category_id,matchday_id,home_team_id,away_team_id,stage,status) values(c,d,a,b,'REGULAR','PROGRAMADO') returning id into regular1;
 insert into public.matches(category_id,matchday_id,home_team_id,away_team_id,stage,status) values(c,d,x,y,'REGULAR','PROGRAMADO') returning id into regular2;
 insert into public.matches(category_id,matchday_id,home_team_id,away_team_id,stage,status) values(c,d,b,outsider,'REGULAR','PROGRAMADO') returning id into regular3;
 execute 'reset role';
 rejected:=false;
 begin perform public.close_regular(c); exception when raise_exception then rejected:=true; end;
 assert rejected,'No cerrar con pendientes';
 perform pg_temp.act(regular1,'START'); perform pg_temp.goal(regular1,a); perform pg_temp.goal(regular1,a);
 perform pg_temp.second_half(regular1); perform pg_temp.act(regular1,'FINISH');
 perform pg_temp.act(regular2,'START'); perform pg_temp.goal(regular2,x); perform pg_temp.goal(regular2,y);
 perform pg_temp.second_half(regular2); perform pg_temp.act(regular2,'FINISH');
 perform pg_temp.act(regular3,'START'); perform pg_temp.goal(regular3,b);
 perform pg_temp.second_half(regular3); perform pg_temp.act(regular3,'FINISH');
 select array_agg(team_id order by position) into qualified from (select * from public.get_standings(c,false) order by position limit 4) q;
 execute 'set local role anon'; perform public.close_regular(c); execute 'reset role';
 assert (select qualified_team_ids from public.categories where id=c)=qualified;
 assert not outsider=any(qualified);
 rejected:=false;
 begin update public.matches set phase_elapsed_seconds=899 where id=regular1; exception when raise_exception then rejected:=true; end;
 assert rejected,'Regular congelada';
 rejected:=false;
 begin insert into public.match_events(match_id,team_id,period,clock_seconds) values(regular1,a,'PRIMER_TIEMPO',1); exception when raise_exception then rejected:=true; end;
 assert rejected,'Eventos regulares congelados';
 rejected:=false;
 begin perform public.create_semifinals(c,a,b,x,outsider); exception when raise_exception then rejected:=true; end;
 assert rejected,'Top 4 obligatorio';
 rejected:=false;
 begin perform public.create_semifinals(c,a,b,x,a); exception when raise_exception then rejected:=true; end;
 assert rejected,'Sin equipos repetidos';
 execute 'set local role anon'; perform public.create_semifinals(c,a,b,x,y); perform public.create_semifinals(c,a,b,x,y); execute 'reset role';
 assert (select count(*) from public.matches where category_id=c and stage='SEMIFINAL')=2;
 select id into strict sf1 from public.matches where category_id=c and stage='SEMIFINAL' and home_team_id=a;
 select id into strict sf2 from public.matches where category_id=c and stage='SEMIFINAL' and home_team_id=x;
 rejected:=false;
 begin perform public.generate_day6(c); exception when raise_exception then rejected:=true; end;
 assert rejected,'Jornada 6 prematura';
 perform pg_temp.act(sf1,'START'); perform pg_temp.goal(sf1,a); perform pg_temp.second_half(sf1); perform pg_temp.act(sf1,'FINISH');
 perform pg_temp.act(sf2,'START'); perform pg_temp.goal(sf2,x); perform pg_temp.goal(sf2,y); perform pg_temp.second_half(sf2);
 rejected:=false;
 begin perform pg_temp.act(sf2,'FINISH'); exception when raise_exception then rejected:=true; end;
 assert rejected,'Empate requiere penales';
 rejected:=false;
 begin perform public.set_penalty_winner(sf2,outsider); exception when raise_exception then rejected:=true; end;
 assert rejected,'Penales participante';
 execute 'set local role anon'; perform public.set_penalty_winner(sf2,y); execute 'reset role';
 result:=pg_temp.goal(sf2,x); event_id:=(result->'event'->>'id')::uuid;
 assert (select tiebreak_winner_team_id is null from public.matches where id=sf2),'Gol limpia penales';
 rejected:=false;
 begin perform public.set_penalty_winner(sf2,y); exception when raise_exception then rejected:=true; end;
 assert rejected,'No penales con desigualdad';
 execute 'set local role anon'; perform public.void_goal(sf2,event_id); perform public.set_penalty_winner(sf2,y); execute 'reset role';
 perform pg_temp.act(sf2,'FINISH');
 result:=public.match_outcome(sf2);
 assert result->'score'='{"home":1,"away":1}'::jsonb;
 assert result->>'winner_team_id'=y::text;
 execute 'set local role anon'; perform public.generate_day6(c); perform public.generate_day6(c); execute 'reset role';
 assert (select count(*) from public.matches where category_id=c and stage in ('FINAL','THIRD_PLACE'))=2;
 select id into strict final_id from public.matches where category_id=c and stage='FINAL' and home_team_id=a and away_team_id=y;
 select id into strict third_id from public.matches where category_id=c and stage='THIRD_PLACE' and home_team_id=b and away_team_id=x;
 perform pg_temp.act(final_id,'START'); perform pg_temp.goal(final_id,y); perform pg_temp.second_half(final_id); perform pg_temp.act(final_id,'FINISH');
 perform pg_temp.act(third_id,'START'); perform pg_temp.second_half(third_id);
 execute 'set local role anon'; perform public.set_penalty_winner(third_id,b); execute 'reset role';
 perform pg_temp.act(third_id,'FINISH');
 assert public.match_outcome(final_id)->>'winner_team_id'=y::text,'Campeón';
 assert public.match_outcome(final_id)->>'loser_team_id'=a::text,'Segundo';
 assert public.match_outcome(third_id)->>'winner_team_id'=b::text,'Tercero';
 assert public.match_outcome(third_id)->>'loser_team_id'=x::text,'Cuarto';
 select array_agg(team_id order by position) into qualified from (select * from public.get_standings(c,false) order by position limit 4) q;
 assert (select qualified_team_ids from public.categories where id=c)=qualified,'Playoffs no alteran standings';
 assert (select regular_closed_at is null from public.categories where name='Mujeres'),'Categorías independientes';
 execute 'set local role anon'; result:=public.get_tournament(); execute 'reset role';
 assert jsonb_array_length(result->'matches')>=6;
 assert not has_table_privilege('anon','public.matches','UPDATE');
 assert not has_table_privilege('anon','public.match_events','INSERT');
 assert (select count(*) from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename in ('matches','match_events'))=2;
 raise notice 'OK: regular, Top 4, cruces, penales, limpieza, final, tercero, podio y lecturas públicas.';
end $$;
rollback;
