begin;
do $$ begin
  if exists(select 1 from public.matches where status in ('PRIMER_TIEMPO','SEGUNDO_TIEMPO','DESCANSO','PAUSADO')) then
    raise exception 'Prueba cancelada: existe un partido activo real.';
  end if;
end $$;
create function pg_temp.act(mid uuid,action text) returns jsonb language plpgsql as $$
declare v timestamptz; j jsonb;
begin
  select updated_at into v from public.matches where id=mid;
  execute 'set local role anon'; j:=public.control_match(mid,action,v); execute 'reset role'; return j;
end $$;
create function pg_temp.event(mid uuid,tid uuid,kind text,pid uuid,rid uuid default gen_random_uuid()) returns jsonb language plpgsql as $$
declare j jsonb;
begin
  execute 'set local role anon'; j:=public.record_match_event(mid,tid,kind,pid,rid); execute 'reset role'; return j;
end $$;
do $$
declare c uuid; h uuid; a uuid; d uuid; mid uuid; p uuid; opponent uuid; spare uuid;
  j jsonb; first_goal uuid; rid uuid:=gen_random_uuid(); timeout_request uuid:=gen_random_uuid(); timeout_id uuid;
  legacy uuid; x uuid; y uuid; sf uuid; rejected boolean; tag text:='__players_'||gen_random_uuid()::text;
begin
  insert into public.categories(name) values(tag) returning id into c;
  insert into public.teams(category_id,name) values(c,tag||'h') returning id into h;
  insert into public.teams(category_id,name) values(c,tag||'a') returning id into a;
  execute 'set local role anon';
  insert into public.players(team_id,full_name,shirt_number) values(h,'Carlos López',5) returning id into p;
  insert into public.players(team_id,full_name,shirt_number) values(a,'Pedro Gómez',5) returning id into opponent;
  insert into public.players(team_id,full_name,shirt_number,active) values(h,'Reserva',9,false) returning id into spare;
  execute 'reset role';
  rejected:=false;
  begin
    execute 'set local role anon';
    insert into public.players(team_id,full_name,shirt_number) values(h,'Duplicado',5);
  exception when unique_violation then rejected:=true; end;
  execute 'reset role'; assert rejected,'Dorsal activo único por equipo';
  assert not has_column_privilege('anon','public.players','team_id','UPDATE');
  assert not has_table_privilege('anon','public.players','DELETE');
  select id into strict d from public.matchdays where number=1;
  insert into public.matches(category_id,matchday_id,home_team_id,away_team_id) values(c,d,h,a) returning id into mid;
  rejected:=false;
  begin perform pg_temp.event(mid,h,'GOAL',p); exception when raise_exception then rejected:=true; end;
  assert rejected,'Programado no acepta eventos';
  perform pg_temp.act(mid,'START');
  update public.matches set phase_started_at=clock_timestamp()-interval '480 seconds' where id=mid;
  -- Compatibilidad: goles históricos sin jugador siguen contando.
  j:=public.record_goal(mid,h,gen_random_uuid()); legacy:=(j->'event'->>'id')::uuid;
  j:=pg_temp.event(mid,h,'GOAL',p,rid); first_goal:=(j->'event'->>'id')::uuid;
  assert j->'control'->'score'='{"home":2,"away":0}'::jsonb;
  assert j->'event'->>'player_name'='Carlos López';
  assert j->'event'->>'shirt_number'='5';
  assert (j->'event'->>'clock_seconds')::int between 480 and 490;
  assert j->'event'->>'period'='PRIMER_TIEMPO';
  assert pg_temp.event(mid,h,'GOAL',p,rid)->'event'->>'id'=first_goal::text,'Reintento no duplica';
  assert (select goals from public.get_top_scorers(c) where player_id=p)=1,'Histórico sin jugador no se atribuye';
  rejected:=false;
  begin perform pg_temp.event(mid,h,'GOAL',opponent); exception when raise_exception then rejected:=true; end;
  assert rejected,'Jugador del rival rechazado';
  rejected:=false;
  begin perform pg_temp.event(mid,h,'GOAL',spare); exception when raise_exception then rejected:=true; end;
  assert rejected,'Jugador inactivo rechazado';
  rejected:=false;
  begin perform pg_temp.event(mid,h,'YELLOW_CARD',null); exception when raise_exception then rejected:=true; end;
  assert rejected,'Amarilla requiere jugador';
  rejected:=false;
  begin perform pg_temp.event(mid,h,'GOAL',null); exception when raise_exception then rejected:=true; end;
  assert rejected,'Nuevo gol requiere jugador';
  rejected:=false;
  begin perform pg_temp.event(mid,h,'FOUL',null,rid); exception when raise_exception then rejected:=true; end;
  assert rejected,'UUID no se puede reutilizar para otro evento';
  perform pg_temp.event(mid,h,'YELLOW_CARD',p);
  for i in 1..6 loop perform pg_temp.event(mid,h,'FOUL',null); end loop;
  perform pg_temp.event(mid,a,'FOUL',null);
  assert (select count(*) from public.match_events where match_id=mid and team_id=h and type='FOUL' and period='PRIMER_TIEMPO' and voided_at is null)=6;
  assert public.get_match_control(mid)->'score'='{"home":2,"away":0}'::jsonb,'Faltas y tarjetas no suman goles';
  assert (select goals from public.get_top_scorers(c) where player_id=p)=1;
  j:=pg_temp.event(mid,h,'TIMEOUT',null,timeout_request); timeout_id:=(j->'event'->>'id')::uuid;
  assert pg_temp.event(mid,h,'TIMEOUT',null,timeout_request)->'event'->>'id'=timeout_id::text;
  rejected:=false;
  begin perform pg_temp.event(mid,h,'TIMEOUT',null); exception when raise_exception then rejected:=true; end;
  assert rejected,'Un tiempo muerto por equipo y periodo';
  perform pg_temp.event(mid,a,'TIMEOUT',null);
  execute 'set local role anon';
  update public.players set full_name='Carlos Actualizado',shirt_number=10,active=false where id=p;
  execute 'reset role';
  assert (select player_name from public.match_events where id=first_goal)='Carlos López','Nombre histórico intacto';
  assert (select shirt_number from public.match_events where id=first_goal)=5;
  assert pg_temp.event(mid,h,'GOAL',p,rid)->'event'->>'id'=first_goal::text,'Reintento tras baja conserva evento';
  execute 'set local role anon'; perform public.void_match_event(mid,first_goal); execute 'reset role';
  assert not exists(select 1 from public.get_top_scorers(c) where player_id=p),'Anulado sale de goleadores';
  assert public.get_match_control(mid)->'score'='{"home":1,"away":0}'::jsonb;
  assert pg_temp.event(mid,h,'GOAL',p,rid)->'event'->>'voided_at' is not null;
  perform pg_temp.act(mid,'PAUSE');
  rejected:=false;
  begin perform pg_temp.event(mid,a,'FOUL',null); exception when raise_exception then rejected:=true; end;
  assert rejected,'Pausado no acepta eventos nuevos';
  perform pg_temp.act(mid,'RESUME');
  perform pg_temp.act(mid,'BREAK');
  perform pg_temp.act(mid,'SECOND_HALF');
  assert not exists(select 1 from public.match_events where match_id=mid and period='SEGUNDO_TIEMPO' and type in ('FOUL','TIMEOUT'));
  perform pg_temp.event(mid,h,'TIMEOUT',null);
  perform pg_temp.event(mid,a,'TIMEOUT',null);
  j:=pg_temp.event(mid,a,'GOAL',opponent);
  assert j->'event'->>'period'='SEGUNDO_TIEMPO';
  assert j->'control'->'score'='{"home":1,"away":1}'::jsonb;
  perform pg_temp.act(mid,'FINISH');
  rejected:=false;
  begin perform public.void_match_event(mid,(j->'event'->>'id')::uuid); exception when raise_exception then rejected:=true; end;
  assert rejected,'Finalizado no permite anular';
  assert (select goals from public.get_top_scorers(c) where player_id=opponent)=1;
  assert (select gf from public.get_standings(c,false) where team_id=h)=1,'Tabla conserva gol antiguo';
  assert exists(select 1 from public.match_events where id=legacy and player_id is null),'Gol antiguo intacto';
  -- Eventos sin gol no deben limpiar un ganador por penales ya elegido.
  insert into public.teams(category_id,name) values(c,tag||'x') returning id into x;
  insert into public.teams(category_id,name) values(c,tag||'y') returning id into y;
  update public.categories set regular_closed_at=clock_timestamp(),qualified_team_ids=array[h,a,x,y] where id=c;
  perform public.create_semifinals(c,h,a,x,y);
  select id into strict sf from public.matches where category_id=c and stage='SEMIFINAL' and home_team_id=h;
  perform pg_temp.act(sf,'START'); perform pg_temp.act(sf,'BREAK'); perform pg_temp.act(sf,'SECOND_HALF');
  perform public.set_penalty_winner(sf,h);
  perform pg_temp.event(sf,a,'YELLOW_CARD',opponent);
  perform pg_temp.event(sf,h,'FOUL',null);
  perform pg_temp.event(sf,h,'TIMEOUT',null);
  assert (select tiebreak_winner_team_id from public.matches where id=sf)=h;
  perform pg_temp.act(sf,'FINISH');
  assert public.match_outcome(sf)->>'winner_team_id'=h::text;
  assert exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and tablename='players');
  assert not has_table_privilege('anon','public.match_events','INSERT');
  assert not has_table_privilege('anon','public.match_events','DELETE');
  perform public.delete_match(mid,(select updated_at from public.matches where id=mid));
  assert not exists(select 1 from public.get_top_scorers(c)),'Borrar un partido recalcula goleadores';
  assert (select count(*) from public.players where team_id in (h,a))=3,'Plantillas conservadas';
  raise notice 'OK: plantillas, goles históricos, eventos, periodos, idempotencia y estadísticas.';
end $$;
rollback;
