-- Solo fixtures transaccionales; no conservar datos de prueba.
begin;
do $$ declare c uuid; h uuid; a uuid; d uuid; mid uuid; p uuid; q uuid; unlisted uuid;
  j jsonb; red_id uuid; rid uuid:=gen_random_uuid(); before_events jsonb; rejected boolean;
begin
  if exists(select 1 from public.matches where status not in ('PROGRAMADO','FINALIZADO')) then
    raise exception 'Prueba cancelada: hay un partido activo.';
  end if;
  insert into public.categories(name) values('__red_'||gen_random_uuid()) returning id into c;
  insert into public.teams(category_id,name) values(c,'Local roja') returning id into h;
  insert into public.teams(category_id,name) values(c,'Visitante roja') returning id into a;
  insert into public.players(team_id,full_name) values(h,'Jugador local') returning id into p;
  insert into public.players(team_id,full_name) values(a,'Jugador visitante') returning id into q;
  insert into public.players(team_id,full_name) values(h,'Sin convocatoria') returning id into unlisted;
  select id into strict d from public.matchdays where number=1;
  insert into public.matches(category_id,matchday_id,home_team_id,away_team_id) values(c,d,h,a) returning id into mid;
  set local role anon;
  perform public.set_match_player(mid,p,5,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,q,10,true,(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'START',(select updated_at from public.matches where id=mid));
  perform public.record_match_event(mid,h,'GOAL',p,gen_random_uuid());
  perform public.record_match_event(mid,a,'YELLOW_CARD',q,gen_random_uuid());
  select jsonb_agg(to_jsonb(e) order by id) into before_events from public.match_events e where match_id=mid;
  rejected:=false;
  begin perform public.record_match_event(mid,h,'RED_CARD',null,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'Roja requiere jugador';
  rejected:=false;
  begin perform public.record_match_event(mid,h,'RED_CARD',q,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'Roja no admite jugador visitante para local';
  rejected:=false;
  begin perform public.record_match_event(mid,h,'RED_CARD',unlisted,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'Roja requiere convocatoria';
  j:=public.record_match_event(mid,h,'RED_CARD',p,rid);
  red_id:=(j->'event'->>'id')::uuid;
  assert j->'event'->>'player_name'='Jugador local';
  assert (j->'event'->>'shirt_number')::int=5;
  assert j->'event'->>'period'='PRIMER_TIEMPO';
  assert j->'event'->>'clock_seconds' is not null;
  perform public.record_match_event(mid,h,'RED_CARD',p,rid);
  assert (select count(*) from public.match_events where request_id=rid)=1;
  assert (select jsonb_agg(to_jsonb(e) order by id) from public.match_events e where match_id=mid and type<>'RED_CARD')=before_events;
  assert public.get_match_control(mid)->'score'='{"home":1,"away":0}'::jsonb;
  assert (select goals from public.get_top_scorers(c) where player_id=p)=1;
  assert (select gf from public.get_standings(c,true) where team_id=h)=1;
  perform public.void_match_event(mid,red_id);
  assert (select voided_at is not null from public.match_events where id=red_id);
  perform public.control_match(mid,'BREAK',(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'SECOND_HALF',(select updated_at from public.matches where id=mid));
  j:=public.record_match_event(mid,a,'RED_CARD',q,gen_random_uuid());
  assert j->'event'->>'period'='SEGUNDO_TIEMPO';
  assert (j->'event'->>'shirt_number')::int=10;
  update public.players set active=false where id=p;
  assert (select count(*) from public.players where id=p)=1;
  assert (select goals from public.get_top_scorers(c) where player_id=p)=1,'Baja conserva goles acumulados';
  reset role;
end $$;
rollback;
