begin;
do $$ declare c uuid; h uuid; a uuid; d uuid; mid uuid; p uuid; q uuid; rid uuid:=gen_random_uuid(); j jsonb;
  rejected boolean; first_card uuid; second_card uuid; clock_before timestamptz; i integer;
begin
  if exists(select 1 from public.matches where status not in ('PROGRAMADO','FINALIZADO')) then raise exception 'Hay partido activo; prueba cancelada.'; end if;
  insert into public.categories(name) values('__management_'||gen_random_uuid()) returning id into c;
  insert into public.teams(category_id,name) values(c,'Local control') returning id into h;
  insert into public.teams(category_id,name) values(c,'Visitante control') returning id into a;
  insert into public.players(team_id,full_name) values(h,'Juan') returning id into p;
  insert into public.players(team_id,full_name) values(a,'Pedro') returning id into q;
  select id into strict d from public.matchdays where number=1;
  insert into public.matches(category_id,matchday_id,home_team_id,away_team_id) values(c,d,h,a) returning id into mid;
  set local role anon;
  rejected:=false;
  begin perform public.control_match(mid,'START',(select updated_at from public.matches where id=mid)); exception when raise_exception then rejected:=true; end;
  assert rejected,'Inicio exige control previo';
  rejected:=false;
  begin perform public.save_match_precheck(mid,null,true,true,false,(select updated_at from public.matches where id=mid)); exception when raise_exception then rejected:=true; end;
  assert rejected,'Respuestas incompletas rechazadas';
  perform public.save_match_precheck(mid,true,true,false,false,(select updated_at from public.matches where id=mid));
  assert public.get_match_control(mid)->'precheck'->>'away_ball'='false';
  perform public.save_match_precheck(mid,true,true,false,false,null); -- Reintento confirmado.
  assert (select count(*) from public.match_prechecks where match_id=mid)=1;
  perform public.set_match_player(mid,p,5,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,q,10,true,(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'START',(select updated_at from public.matches where id=mid));
  select phase_started_at into clock_before from public.matches where id=mid;
  perform public.record_match_event(mid,h,'GOAL',p,gen_random_uuid());
  perform public.record_match_event(mid,h,'FOUL',null,rid);
  perform public.record_match_event(mid,h,'FOUL',null,rid);
  assert (select count from public.match_foul_counters where match_id=mid)=1;
  assert not exists(select 1 from public.match_events where match_id=mid and type='FOUL');
  for i in 1..5 loop perform public.record_match_event(mid,h,'FOUL',null,gen_random_uuid()); end loop;
  assert public.get_match_control(mid)->'fouls' @> jsonb_build_array(jsonb_build_object('team_id',h,'period_number',1,'count',6));
  rejected:=false;
  begin perform public.record_match_event(mid,a,'FOUL',null,rid); exception when raise_exception then rejected:=true; end;
  assert rejected,'Misma solicitud no cambia de equipo';
  j:=public.record_match_event(mid,h,'YELLOW_CARD',p,gen_random_uuid()); first_card:=(j->'event'->>'id')::uuid;
  assert (select phase_started_at from public.matches where id=mid)=clock_before;
  perform public.control_match(mid,'BREAK',(select updated_at from public.matches where id=mid));
  assert public.get_match_control(mid)->'precheck'->>'away_band'='false';
  assert public.get_match_control(mid)->'events' @> jsonb_build_array(jsonb_build_object('id',first_card,'type','YELLOW_CARD','period_number',1));
  perform public.control_match(mid,'SECOND_HALF',(select updated_at from public.matches where id=mid));
  assert not exists(select 1 from public.match_foul_counters where match_id=mid and period='SEGUNDO_TIEMPO');
  perform public.record_match_event(mid,h,'FOUL',null,gen_random_uuid());
  assert public.get_match_control(mid)->'fouls' @> jsonb_build_array(jsonb_build_object('team_id',h,'period_number',2,'count',1));
  j:=public.record_match_event(mid,h,'YELLOW_CARD',p,gen_random_uuid()); second_card:=(j->'event'->>'id')::uuid;
  assert j->'event'->>'shirt_number'='5';
  rejected:=false;
  begin perform public.record_match_event(mid,h,'GOAL',p,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'Doble amarilla impide nuevas acciones solo en el encuentro';
  perform public.void_match_event(mid,second_card);
  perform public.record_match_event(mid,h,'GOAL',p,gen_random_uuid());
  select phase_started_at into clock_before from public.matches where id=mid;
  perform public.record_match_event(mid,a,'RED_CARD',q,gen_random_uuid());
  assert (select status from public.matches where id=mid)='SEGUNDO_TIEMPO';
  assert (select phase_started_at from public.matches where id=mid)=clock_before,'Roja directa no pausa ni reinicia';
  assert (select active from public.players where id=q),'No modifica plantilla';
  perform public.record_match_event(mid,h,'TIMEOUT',null,gen_random_uuid());
  assert (select status from public.matches where id=mid)='TIEMPO_MUERTO';
  rejected:=false;
  begin perform public.record_match_event(mid,h,'FOUL',null,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'No incrementar faltas durante minuto';
  perform public.control_match(mid,'END_TIMEOUT',(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'FINISH',(select updated_at from public.matches where id=mid));
  assert public.get_match_control(mid)->'score'='{"home":2,"away":0}'::jsonb;
  assert not has_table_privilege('anon','public.match_foul_counters','INSERT');
  assert not has_table_privilege('anon','public.match_prechecks','UPDATE');
  reset role;
  select id into strict d from public.matchdays where number=2;
  insert into public.matches(category_id,matchday_id,home_team_id,away_team_id) values(c,d,h,a) returning id into mid;
  set local role anon;
  perform public.save_match_precheck(mid,true,true,true,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,p,7,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,q,9,true,(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'START',(select updated_at from public.matches where id=mid));
  perform public.record_match_event(mid,a,'GOAL',q,gen_random_uuid());
  assert public.get_match_control(mid)->'score'='{"home":0,"away":1}'::jsonb,'Roja previa no bloquea otro partido';
  reset role;
end $$;
rollback;
