begin;
do $$ declare c uuid; h uuid; a uuid; d uuid; mid uuid; p uuid; q uuid; g uuid; red uuid; yellow uuid;
  j jsonb; previous_clock jsonb; first_minute uuid; second_minute uuid; saved int; rejected boolean;
begin
  if exists(select 1 from public.matches where status not in ('PROGRAMADO','FINALIZADO')) then raise exception 'Hay un partido activo; prueba cancelada.'; end if;
  insert into public.categories(name) values('__revert_'||gen_random_uuid()) returning id into c;
  insert into public.teams(category_id,name) values(c,'Local reversión') returning id into h;
  insert into public.teams(category_id,name) values(c,'Visitante reversión') returning id into a;
  insert into public.players(team_id,full_name) values(h,'Juan') returning id into p;
  insert into public.players(team_id,full_name) values(a,'Pedro') returning id into q;
  select id into strict d from public.matchdays where number=1;
  insert into public.matches(category_id,matchday_id,home_team_id,away_team_id) values(c,d,h,a) returning id into mid;
  set local role anon;
  perform public.save_match_precheck(mid,true,true,true,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,p,5,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,q,10,true,(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'START',(select updated_at from public.matches where id=mid));
  j:=public.record_match_event(mid,h,'GOAL',p,gen_random_uuid()); g:=(j->'event'->>'id')::uuid;
  previous_clock:=public.get_match_control(mid)->'match';
  j:=public.record_match_event(mid,h,'RED_CARD',p,gen_random_uuid()); red:=(j->'event'->>'id')::uuid;
  assert public.get_match_control(mid)->'match'=previous_clock,'Roja no cambia reloj ni estado';
  rejected:=false;
  begin perform public.record_match_event(mid,h,'GOAL',p,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected;
  perform public.void_match_event(mid,red);
  perform public.void_match_event(mid,red);
  perform public.record_match_event(mid,h,'GOAL',p,gen_random_uuid());
  assert (select active from public.players where id=p);
  assert (select active from public.match_players where match_id=mid and player_id=p);
  perform public.record_match_event(mid,h,'YELLOW_CARD',p,gen_random_uuid());
  perform public.control_match(mid,'BREAK',(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'SECOND_HALF',(select updated_at from public.matches where id=mid));
  j:=public.record_match_event(mid,h,'YELLOW_CARD',p,gen_random_uuid()); yellow:=(j->'event'->>'id')::uuid;
  perform public.void_match_event(mid,yellow);
  perform public.record_match_event(mid,h,'GOAL',p,gen_random_uuid());
  j:=public.record_match_event(mid,h,'TIMEOUT',null,gen_random_uuid()); first_minute:=(j->'event'->>'id')::uuid;
  perform public.control_match(mid,'END_TIMEOUT',(select updated_at from public.matches where id=mid));
  j:=public.record_match_event(mid,a,'TIMEOUT',null,gen_random_uuid()); second_minute:=(j->'event'->>'id')::uuid;
  saved:=(j->'control'->'match'->>'phase_elapsed_seconds')::int;
  perform public.void_match_event(mid,first_minute);
  assert (select status from public.matches where id=mid)='TIEMPO_MUERTO','Revertir minuto anterior no termina el actual';
  perform public.void_match_event(mid,second_minute);
  assert (select status from public.matches where id=mid)='SEGUNDO_TIEMPO';
  assert (select phase_elapsed_seconds from public.matches where id=mid)=saved;
  previous_clock:=public.get_match_control(mid)->'match';
  perform public.void_match_event(mid,second_minute);
  assert public.get_match_control(mid)->'match'=previous_clock,'Reintento no reinicia el reloj';
  perform public.record_match_event(mid,a,'TIMEOUT',null,gen_random_uuid());
  perform public.control_match(mid,'END_TIMEOUT',(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'FINISH',(select updated_at from public.matches where id=mid));
  previous_clock:=public.get_match_control(mid)->'match';
  perform public.void_match_event(mid,g);
  assert public.get_match_control(mid)->'score'='{"home":2,"away":0}'::jsonb;
  assert public.get_match_control(mid)->'match'=previous_clock,'Reversión finalizada no reabre ni modifica reloj';
  assert (select goals from public.get_top_scorers(c) where player_id=p)=2;
  assert (select gf from public.get_standings(c,true) where team_id=h)=2;
  assert (select voided_at is not null from public.match_events where id=g),'Se conserva fila histórica';
  reset role;
  -- El cierre de clasificación conserva su protección; las tarjetas no cambian clasificados.
  update public.categories set regular_closed_at=clock_timestamp(),qualified_team_ids=array[h,a,h,a] where id=c;
  set local role anon;
  select id into g from public.match_events where match_id=mid and type='GOAL' and voided_at is null limit 1;
  rejected:=false;
  begin perform public.void_match_event(mid,g); exception when raise_exception then rejected:=true; end;
  assert rejected,'No altera clasificación cerrada';
  select id into yellow from public.match_events where match_id=mid and type='YELLOW_CARD' and voided_at is null limit 1;
  perform public.void_match_event(mid,yellow);
  assert (select voided_at is not null from public.match_events where id=yellow);
  reset role;
end $$;
rollback;
