begin;
do $$ declare c uuid; h uuid; a uuid; p uuid; q uuid; mid uuid; d uuid; e uuid; rows jsonb; result jsonb;
begin
 insert into public.categories(name) values('__initial_import_test') returning id into c;
 insert into public.teams(category_id,name) values(c,'Import home') returning id into h;
 insert into public.teams(category_id,name) values(c,'Import away') returning id into a;
 rows:=jsonb_build_array(jsonb_build_object('team_id',h,'player_name','  Juan   Pérez  ','goals',3));
 result:=public.import_initial_players(rows,'fixture');
 p:=(result->0->>'player_id')::uuid;
 perform public.import_initial_players(rows,'retry');
 assert (select count(*) from public.players where team_id=h)=1,'No duplica jugadores';
 assert (select goals from public.player_initial_goals where player_id=p)=3,'No duplica saldo';
 update public.players set active=false where id=p;
 perform public.import_initial_players(jsonb_build_array(jsonb_build_object('team_id',h,'player_name','JUAN PÉREZ','goals',3)),'retry');
 assert not (select active from public.players where id=p),'No reactiva jugadores existentes';
 assert (select goals from public.get_top_scorers(c) where player_id=p)=3,'Inactivos conservan goles';
 begin
   perform public.import_initial_players(jsonb_build_array(jsonb_build_object('team_id',h,'player_name','Nuevo'),jsonb_build_object('team_id',h,'player_name','Juan Pérez','goals',4)),'conflict');
   raise exception 'FAIL: aceptó otro saldo';
 exception when raise_exception then if SQLERRM like 'FAIL:%' then raise; end if; end;
 assert (select count(*) from public.players where team_id=h)=1,'Carga fallida es atómica';
 assert not has_function_privilege('anon','public.import_initial_players(jsonb,text)','EXECUTE'),'Importación no pública';
 assert has_table_privilege('anon','public.player_initial_goals','SELECT');
 assert not has_table_privilege('anon','public.player_initial_goals','INSERT');
 update public.players set active=true where id=p;
 result:=public.import_initial_players(jsonb_build_array(jsonb_build_object('team_id',a,'player_name','Oponente')),'fixture');
 q:=(result->0->>'player_id')::uuid;
 select id into d from public.matchdays where number=1;
 insert into public.matches(category_id,matchday_id,home_team_id,away_team_id) values(c,d,h,a) returning id into mid;
 perform public.save_match_precheck(mid,true,true,true,true,(select updated_at from public.matches where id=mid));
 perform public.set_match_player(mid,p,5,true,(select updated_at from public.matches where id=mid));
 perform public.set_match_player(mid,q,10,true,(select updated_at from public.matches where id=mid));
 perform public.control_match(mid,'START',(select updated_at from public.matches where id=mid));
 result:=public.record_match_event(mid,h,'GOAL',p,gen_random_uuid()); e:=(result->'event'->>'id')::uuid;
 assert (select goals from public.get_top_scorers(c) where player_id=p)=4,'Saldo más gol válido';
 assert public.get_match_control(mid)->'score'->>'home'='1','Saldo no altera marcador';
 perform public.void_match_event(mid,e);
 assert (select goals from public.get_top_scorers(c) where player_id=p)=3,'Reversión conserva saldo inicial';
 assert not exists(select 1 from information_schema.columns where table_schema='public' and table_name='players' and column_name='shirt_number');
end $$;
rollback;
