begin;
do $$ declare c uuid; h uuid; a uuid; mid uuid; p uuid; q uuid; rid uuid:=gen_random_uuid(); j jsonb; eid uuid; rejected boolean; before_count bigint; replacement uuid; original jsonb; kind text;
begin
  insert into public.categories(name) values('__own_'||gen_random_uuid()) returning id into c;
  insert into public.teams(category_id,name) values(c,'Local autogol') returning id into h;
  insert into public.teams(category_id,name) values(c,'Visitante autogol') returning id into a;
  insert into public.players(team_id,full_name) values(h,'Jugador local') returning id into p;
  insert into public.players(team_id,full_name) values(a,'Jugador visitante') returning id into q;
  insert into public.matches(category_id,matchday_id,home_team_id,away_team_id) values(c,(select id from public.matchdays where number=1),h,a) returning id into mid;
  insert into public.players(team_id,full_name) values(h,'Otro local') returning id into replacement;
  set local role anon;
  rejected:=false;
  begin perform public.record_own_goal(mid,h,rid); exception when raise_exception then rejected:=true; end;
  assert rejected,'Rechaza partido programado';
  perform public.save_match_precheck(mid,true,true,true,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,p,5,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,q,10,true,(select updated_at from public.matches where id=mid));
  perform public.set_match_player(mid,replacement,8,true,(select updated_at from public.matches where id=mid));
  perform public.control_match(mid,'START',(select updated_at from public.matches where id=mid));
  rejected:=false;
  begin perform public.record_match_event(mid,h,'GOAL',null,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'Gol normal sigue exigiendo jugador';
  rejected:=false;
  begin perform public.record_own_goal(mid,gen_random_uuid(),gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'Rechaza equipo ajeno';
  select count(*) into before_count from public.players;
  j:=public.record_own_goal(mid,h,rid); eid:=(j->'event'->>'id')::uuid;
  assert j->'control'->'score'->>'home'='1';
  assert j->'event'->>'player_id' is null and j->'event'->>'shirt_number' is null;
  assert j->'event'->>'player_name'='Autogol' and j->'event'->>'period'='PRIMER_TIEMPO';
  assert (j->'event'->>'clock_seconds')::int between 0 and 900;
  assert (public.record_own_goal(mid,h,rid)->'event'->>'id')::uuid=eid;
  assert (select count(*) from public.match_events where request_id=rid)=1;
  assert not exists(select 1 from public.get_top_scorers(c));
  assert (select count(*) from public.players)=before_count;
  rejected:=false;
  begin perform public.record_own_goal(mid,a,rid); exception when raise_exception then rejected:=true; end;
  assert rejected,'Reintento no puede cambiar de equipo';

  foreach kind in array array['GOAL','YELLOW_CARD','RED_CARD'] loop
    j:=public.record_match_event(mid,h,kind,p,gen_random_uuid()); original:=j->'event';
    rejected:=false;
    begin perform public.edit_match_event_player(mid,(original->>'id')::uuid,q,p); exception when raise_exception then rejected:=true; end;
    assert rejected,'No permite cambiar de equipo';
    j:=public.edit_match_event_player(mid,(original->>'id')::uuid,replacement,p);
    assert ((j->'event')-array['player_id','player_name','shirt_number'])=(original-array['player_id','player_name','shirt_number']);
    assert j->'event'->>'player_id'=replacement::text;
    assert j->'event'->>'shirt_number'='8';
    assert public.edit_match_event_player(mid,(original->>'id')::uuid,replacement,p)->'event'=j->'event','Reintento idempotente';
    if kind='GOAL' then
      assert j->'control'->'score'->>'home'='2';
      assert (select goals from public.get_top_scorers(c) where player_id=replacement)=1;
      assert not exists(select 1 from public.get_top_scorers(c) where player_id=p);
    end if;
    if kind='RED_CARD' then
      assert not exists(select 1 from public.match_events where match_id=mid and player_id=p and type='RED_CARD' and voided_at is null);
      assert exists(select 1 from public.match_events where match_id=mid and player_id=replacement and type='RED_CARD' and voided_at is null);
    end if;
    perform public.void_match_event(mid,(original->>'id')::uuid);
    assert (select voided_at is not null from public.match_events where id=(original->>'id')::uuid);
    assert not exists(select 1 from public.match_events where match_id=mid and player_id=replacement and voided_at is null);
    assert not exists(select 1 from public.get_top_scorers(c));
    assert public.get_match_control(mid)->'score'->>'home'='1';
  end loop;
  perform public.void_match_event(mid,eid);
  assert public.get_match_control(mid)->'score'->>'home'='0','Autogol anulado';

  perform public.record_match_event(mid,h,'GOAL',p,gen_random_uuid());
  assert (select goals from public.get_top_scorers(c) where player_id=p)=1;
  perform public.control_match(mid,'BREAK',(select updated_at from public.matches where id=mid));
  rejected:=false;
  begin perform public.record_own_goal(mid,a,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'Rechaza descanso';
  perform public.control_match(mid,'SECOND_HALF',(select updated_at from public.matches where id=mid));
  j:=public.record_own_goal(mid,a,gen_random_uuid());
  assert j->'event'->>'period'='SEGUNDO_TIEMPO';
  assert j->'control'->'score'->>'away'='1';
  assert j->'control'->'score'->>'home'='1';
  perform public.control_match(mid,'FINISH',(select updated_at from public.matches where id=mid));
  rejected:=false;
  begin perform public.record_own_goal(mid,a,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
  assert rejected,'Rechaza finalizado';
  assert (public.record_own_goal(mid,h,rid)->'event'->>'id')::uuid=eid;
end $$;
rollback;
