-- Transactional local fixtures only. Never execute on production.
begin;
do $$ declare c uuid; h uuid; a uuid; t3 uuid; t4 uuid; p uuid; q uuid; mid uuid; sf uuid; wo uuid;
 j jsonb; before_j jsonb; rid uuid:=gen_random_uuid(); rejected boolean; event_id uuid;
begin
 insert into public.categories(name) values('__penalty_'||gen_random_uuid()) returning id into c;
 insert into public.teams(category_id,name) values(c,'A') returning id into h;
 insert into public.teams(category_id,name) values(c,'B') returning id into a;
 insert into public.teams(category_id,name) values(c,'C') returning id into t3;
 insert into public.teams(category_id,name) values(c,'D') returning id into t4;
 insert into public.players(team_id,full_name) values(h,'Local') returning id into p;
 insert into public.players(team_id,full_name) values(a,'Visita') returning id into q;
 insert into public.matches(category_id,matchday_id,home_team_id,away_team_id)
 values(c,(select id from public.matchdays where number=4),h,a) returning id into mid;
 set local role anon;
 rejected:=false;
 begin perform public.start_penalty_shootout(mid,h,rid,(select updated_at from public.matches where id=mid)); exception when raise_exception then rejected:=true; end;
 assert rejected,'No inicia en regular';
 perform public.save_match_precheck(mid,true,true,true,true,(select updated_at from public.matches where id=mid));
 perform public.set_match_player(mid,p,1,true,(select updated_at from public.matches where id=mid));
 perform public.set_match_player(mid,q,2,true,(select updated_at from public.matches where id=mid));
 perform public.control_match(mid,'START',(select updated_at from public.matches where id=mid));
 perform public.control_match(mid,'BREAK',(select updated_at from public.matches where id=mid));
 perform public.control_match(mid,'SECOND_HALF',(select updated_at from public.matches where id=mid));
 perform public.control_match(mid,'FINISH',(select updated_at from public.matches where id=mid));
 perform public.close_regular(c);
 perform public.create_semifinals(c,h,a,t3,t4);
 select id into sf from public.matches where category_id=c and stage='SEMIFINAL' and home_team_id=h;
 select id into wo from public.matches where category_id=c and stage='SEMIFINAL' and home_team_id=t3;
 perform public.record_walkover(wo,t4,gen_random_uuid(),(select updated_at from public.matches where id=wo));
 rejected:=false;
 begin perform public.start_penalty_shootout(wo,t3,gen_random_uuid(),(select updated_at from public.matches where id=wo)); exception when raise_exception then rejected:=true; end;
 assert rejected,'W.O. no inicia penales';
 perform public.save_match_precheck(sf,true,true,true,true,(select updated_at from public.matches where id=sf));
 perform public.set_match_player(sf,p,1,true,(select updated_at from public.matches where id=sf));
 perform public.set_match_player(sf,q,2,true,(select updated_at from public.matches where id=sf));
 perform public.control_match(sf,'START',(select updated_at from public.matches where id=sf));
 perform public.control_match(sf,'BREAK',(select updated_at from public.matches where id=sf));
 perform public.control_match(sf,'SECOND_HALF',(select updated_at from public.matches where id=sf));
 rejected:=false;
 begin perform public.start_penalty_shootout(sf,a,rid,(select updated_at from public.matches where id=sf)); exception when raise_exception then rejected:=true; end;
 assert rejected,'No inicia antes de terminar reglamentario';
 reset role;
 update public.matches set phase_started_at=clock_timestamp()-interval '901 seconds' where id=sf;
 set local role anon;
 j:=public.record_match_event(sf,h,'GOAL',p,gen_random_uuid());
 event_id:=(j->'event'->>'id')::uuid;
 rejected:=false;
 begin perform public.start_penalty_shootout(sf,a,rid,(select updated_at from public.matches where id=sf)); exception when raise_exception then rejected:=true; end;
 assert rejected,'No inicia sin empate';
 perform public.void_match_event(sf,event_id);
 before_j:=public.get_match_control(sf);
 j:=public.start_penalty_shootout(sf,a,rid,(select updated_at from public.matches where id=sf));
 assert j->'shootout'->>'first_team_id'=a::text,'Puede comenzar visitante';
 assert j->'match'->>'status'='PAUSADO','Reloj detenido';
 rejected:=false;
 begin perform public.record_match_event(sf,h,'GOAL',p,gen_random_uuid()); exception when raise_exception then rejected:=true; end;
 assert rejected,'Tanda bloquea goles reglamentarios nuevos';
 rejected:=false;
 begin insert into public.penalty_shootout_attempts(match_id,team_id,sequence,converted,request_id) values(sf,a,1,true,gen_random_uuid()); exception when insufficient_privilege then rejected:=true; end;
 assert rejected,'No escrituras directas anon';
 j:=public.manage_penalty_shootout(sf,'RECORD',a,null,true,gen_random_uuid(),0);
 assert j->'shootout'->>'next_team_id'=h::text;
 j:=public.manage_penalty_shootout(sf,'RECORD',h,null,false,gen_random_uuid(),1);
 j:=public.manage_penalty_shootout(sf,'FINISH',null,null,null,gen_random_uuid(),2);
 assert j->'shootout'->'score'='{"home":0,"away":1}'::jsonb;
 assert j->'match'->>'tiebreak_winner_team_id'=a::text;
 assert j->'score'=before_j->'score' and j->'events'=before_j->'events';
 assert public.match_outcome(sf)->>'winner_team_id'=a::text;
 perform public.generate_day6(c);
 assert exists(select 1 from public.matches where category_id=c and stage='FINAL' and home_team_id=a and away_team_id=t3);
 assert exists(select 1 from public.matches where category_id=c and stage='THIRD_PLACE' and home_team_id=h and away_team_id=t4);
 assert exists(select 1 from jsonb_array_elements(public.get_tournament()->'matches') x where x->'match'->>'id'=sf::text and x->'shootout'->'score'='{"home":0,"away":1}'::jsonb);
 assert not exists(select 1 from public.get_top_scorers(c));
 assert (select count(*) from pg_publication_tables where pubname='supabase_realtime' and tablename in('penalty_shootouts','penalty_shootout_attempts'))=2;
 reset role;
 assert (select count(*) from public.penalty_shootout_operations where match_id=sf)=3,'Historial de operaciones';
end $$;
rollback;
